# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Gravity_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Gravity

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Gravity:
ifneq (,$(Gravity_config))
	@echo "==== Building Gravity ($(Gravity_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(Gravity_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Gravity"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"